### ISSUE TITLE
MTEX

### ISSUE THREAD

**Issue by ralfHielscher** [Blackbelt1221/Ti-VPSC-CoRotation-Analysis#1]
Hi Ben, Hi Tori,

during the recent MTEX workshop https://www-user.tu-chemnitz.de/~rahi/mtexWorkshop21/index.php many participants expressed their need of an MTEX to VPSC. Looking at your repository it seems close to what they want. 

I could imagine several ways how to proceed:
* advertise you package at  https://mtex-toolbox.github.io/addons
* including an example usage of you package at the MTEX workshop
* including your code into MTEX, while preserving your full authorship and including you into the list of MTEX developers https://mtex-toolbox.github.io/people

It would be nice if you could send me an email about your thoughts.

All the best,

Ralf.

**Comment by tori-miller** [comment]
I have sent you an email to your university account discussing our recent progress and a proposed avenue forward!
